const quotes = {
    Motivational: [
        "Hate only wins if you let it. -Michael Geist",
         "If you think the price of winning is too high, wait till you get the bill from regret. -Tim Grover",
         "When you're good at something, you'll tell everyone. But when you're great at something, they'll tell you.",
         "If your absence doesn't bother them, your presence never meant anything to them. -Dido Stargaze",
        "Sometimes you think that all you want is to disappear, but all you really want is to be found.",
        "The prettiest smiles hides the deepest secrets. The prettiest eyes have cried the most tears, and the kindest hearts have felt the most pain.",
         "Don't climb mountains for the world to see you, but for you to see the world. -David McCullough Jr.",
         "Birds born in a cage think flying is an illness. -Alejandro Jodorowsky",
         "Wisdom cannot be granted, it must be earned. sometimes, at a cost. -Optimus Prime",
         "If you fake bravery when you're terrified, that's bravery. Motivation is the same thing. If you do the thing when you're feeling unmotivated, that is motivation. -Chris Williamson",
         "Life will humble you, no matter how much you think you've achieved life will always find a way to cut you down at your knees. So instead of constantly chasing the big things, start valuing the little moments. -Jordan Ferrone",
        "When the devil ignores you, then you know you're doing something wrong. But, when the devil comes at you, it's because you're trying to do something right. -Denzel Washington",
         "Arrogance breeds complacency and complacency breeds failure. -Andrew Tate",
         "Don't listen to the advice of people who are living lives you don't want to live. -Curtis Fox",
         "The only thing we can do is take it one day at a time. You know that's all we can do. No one is perfect. Everyday we strive to be perfectionists. But no one's perfect. -Floyd Mayweather",
         "High standards protect you from low-quality experiences. -Grant Cardone",
         "Arrogance breeds complacency and complacency breeds failure.",
         "Don't listen to the advice of people who are living lives you don't want to live.",
         "If the people in your circle don't inspire you. They're not your circle. They're your cage.",
         "If you want the happy tomorrows, you need the truths that hurt today. -Matt Mastro",
         "The man who goes to the gym every single day regardless of how he feels will always beat the man who goes to the gym when he feels like going to the gym.",
         "Never let the sadness of the past and the fear of the future ruin the happiness of the present.",
         "If your dreams seem unreachable, don't lower your dreams, raise your effort. -Ellen Sirleaf",
         "The longer it takes to happen, the more you'll appreciate it when it does.",
         "I have never seen a hater doing better than me",
         "Arrogance breeds complacency and complacency breeds failure. -Andrew Tate",
         "Accept what is, let go of what was, and have faith in what will be. -Sonia Ricotti",
         "Don't let someone else's opinion of you become your reality. -Les Brown",
         "The only people you owe your loyalty to are the ones who never made you question theirs.",
         "What consumes your mind controls your life. -Kate Hewitt",
         "Difficult roads lead to beautiful places. -Zig Ziglar",
         "unlikely is certainty waiting for its turn. -Markiplier",
         "If they don't appreciate what you bring to the table, let them eat alone. -Pastor Mike Jr.",
         "Don't let your loyalty become slavery. -Alessandra Ambrosio",
         "Never let your emotions overpower your intelligence. -Morgan Freeman",
         "Hate comes from intimidation, love comes from appreciation. -Stephen Rhodes",
         "Don't fight stupid people for they will drag you down to their level then beat you with experience. -Mark Twain",
         "One day the people that don't even believe in you will tell everyone how they met you. -Johnny Depp",
         "Respect is earned. Honesty is appreciated. Trust is gained. Loyalty is returned. -Zig Ziglar",
         "Never let someone who hasn't walked in your shoes tell you how to tie them.",
         "There will be Haters, Doubters, and Non-Believers, and then there will be you proving them wrong -Jennifer Van Allen",
         "The hardest questions answers are always right in front of us, it just takes the right perspective to see it.",
         "Say what you feel and what you think because those that matter don't mind and those that mind, don't matter -Bernard Baruch",
          "Whatever you do, do it wisely and keep in mind of your purpose",
          "Resist the first elements of passion, it's too late when you resort to medicine",
          "Don't cry about memories, smile because it happened -Dr.Seuss",
          "Confuse them with your silence, shock them with your actions",
          "Success is not final, failure is not fatal: it is the courage to continue that counts. -Winston Churchill",
          "The truth of the matter is that you always know the right thing to do. The hard part is doing it. -General Norman Schwarzkopf",
          "Success is how high you bounce when you hit bottom. -General George S. Patton",
          "Life is 10% what happens to you and 90% how you react to it. -Charles R. Swindoll",
          "Pressure? Nah. Fam, this is just playing ball. Pressure is the homeless man, who doesn't know where his next meal is coming from. Pressure is the single mom, who is trying to scuffle and pay her rent. We get paid a lot of money to play a game. Don't get me wrong - there are challenges. But to call it pressure is almost an insult to regular people. -DAMIAN LILLARD",
          "Believe you can and you're halfway there.",
          "Your limitation—it's only your imagination.",
          "Push yourself, because no one else is going to do it for you.",
          "Great things never come from comfort zones.",
          "Dream it. Wish it. Do it.",
          "Success doesn’t just find you. You have to go out and get it.",
          "The harder you work for something, the greater you’ll feel when you achieve it.",
          "Dream bigger. Do bigger.",
          "Don’t stop when you’re tired. Stop when you’re done.",
          "Wake up with determination. Go to bed with satisfaction.",
          "Do something today that your future self will thank you for.",
          "Little things make big days.",
          "It’s going to be hard, but hard does not mean impossible.",
          "Don’t wait for opportunity. Create it.",
          "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
          "The key to success is to focus on goals, not obstacles.",
          "Dream it. Believe it. Build it.",
          "Hard work beats talent when talent doesn’t work hard.",
          "Stay focused and never give up.",
          "Success is not final, failure is not fatal: It is the courage to continue that counts.", 
          "Be the change that you wish to see in the world. -Mahatma Gandhi",
    ],
    Historical: [
        "If you look for truth you might find comfort in the end but if you look for comfort you will find neither truth nor comfort only soft soap and wishful thinking to begin with and in the end despair. -C.S. Lewis",
         "You may encounter many defeats, but you must not be defeated. In fact, it may be necessary to encounter the defeats, so you can know who you are, what you can rise from, how you can still come out of it. -Dr. Maya Angelou",
         "Freedom will only come when you no longer trade your time for money. -Benjamin Franklin",
         "Dream as if you'll live forever, live as if you'll die today. -James Dean",
         "Hard times create strong men, strong men create good times, good times create weak men, and weak men create hard times. -G. Michael Hopf.",
         "Perfect is the enemy of good. -Voltaire",
         "If you want something you never had, you have to do something you've never done. -Thomas Jefferson",
         "It's not the years in the life it's the life in the years -Honest Abe.",
          "Without training they lacked knowledge without knowledge they lacked confidence without confidence they lacked victory. -Julius Cesar",
          "If a man plays the fool, then it's only fool's he'll persuade, but appear to be the devil... then all men will submit -Blackbeard",
          "A brave man is a man who dares to look the Devil in the face and tell him he is a Devil. -BlackBeard",
          "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
          "I have a dream. - Martin Luther King Jr.",
          "Give me liberty, or give me death! - Patrick Henry",
          "The die is cast. - Julius Caesar",
          "An eye for an eye only ends up making the whole world blind. - Mahatma Gandhi",
          "History is written by the victors. - Winston Churchill",
          "Those who do not learn history are doomed to repeat it. - George Santayana",
          "Injustice anywhere is a threat to justice everywhere. - Martin Luther King Jr.",
          "Let them eat cake. - Marie Antoinette (attributed, but disputed)",
          "To be prepared for war is one of the most effective means of preserving peace. - George Washington",
          "The ballot is stronger than the bullet. - Abraham Lincoln",
          "The pen is mightier than the sword. - Edward Bulwer-Lytton",
          "We hold these truths to be self-evident, that all men are created equal. - Declaration of Independence",
          "The unexamined life is not worth living. - Socrates",
          "Knowledge is power. - Francis Bacon",
          "I came, I saw, I conquered. - Julius Caesar",
          "Power tends to corrupt, and absolute power corrupts absolutely. - Lord Acton",
          "Liberty, equality, fraternity. - French Revolution slogan",
          "Ask not what your country can do for you – ask what you can do for your country. - John F. Kennedy",
          "The only true wisdom is in knowing you know nothing. - Socrates",
          "A smile will get you far, but a smile and a gun will get you farther -Al Capone",
          "I know not with what weapons WW3 will be fought, but WW4 will be fought with sticks and stones. -ALBERT EINSTEIN",
          "Our greatest glory is not in never falling, but in rising every time we fall. -Confucius",
          "There are no extraordinary men... just extraordinary circumstances that ordinary men are forced to deal with. -William Halsey",
          "Fear is the mind-killer. The little-death that brings total obliteration -Paul Atreides", 
    ],
    Funny: [
        "Oh, I don't think I'm a lot dumber than you think that I thought that I thought I was once. - White Goodman",
        "I know you. You know you. You know that I know that I know you. — White Goodman",
        "The naked man fears no pickpocketing. ― Sun Tzu",
        "The inner machinations of my mind are an enigma. - Patrick Star",
        "Happiness is like peeing your pants, everyone can see it but only you can feel its warmth",
        "You gotta live like a sandwich-No matter which way you flip it, bread comes first.",
         "I'm on a seafood diet. I see food and I eat it.",
         "Dads are like boomerangs, I hope",
         "Why don’t skeletons fight each other? They don’t have the guts.",
         "I told my wife she should embrace her mistakes. She hugged me.",
         "Why don’t scientists trust atoms? Because they make up everything!",
         "Parallel lines have so much in common. It’s a shame they’ll never meet.",
         "Why was the math book sad? It had too many problems.",
         "I’m reading a book on anti-gravity. It’s impossible to put down!",
         "Why couldn’t the bicycle stand up by itself? It was two tired.",
         "I told my computer I needed a break, and now it won’t stop sending me Kit-Kats.",
         "Did you hear about the restaurant on the moon? Great food, no atmosphere.",
         "I would avoid the sushi if I was you. It’s a little fishy.",
         "What do you call fake spaghetti? An impasta!",
         "I used to play piano by ear, but now I use my hands.",
         "I told my dog a joke, and he howled with laughter!",
         "I’m friends with all electricians. We have great current conversations.",
         "Why did the scarecrow win an award? Because he was outstanding in his field.",
         "What do you call cheese that isn’t yours? Nacho cheese.",
         "Why don’t eggs tell jokes? They’d crack each other up.",
         "What’s orange and sounds like a parrot? A carrot.",
         "I told my wife she should embrace her mistakes. She gave me a hug.", 
         "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe. -Albert Einstein", 
         "I may be drunk, Miss, but in the morning I will be sober and you will still be ugly. - Winston Churchill",
         "How about another Fortune? SecondFortune.com Lucky Numbers 26, 38, 2, 23, 27, 50. -Fourtune Cookie I opened yesterday", 

    ],
    Space: [
        "We are all made of stardust. - Carl Sagan",
        "Houston, we have a problem. - Apollo 13",
        "That's one small step for man, one giant leap for mankind. - Neil Armstrong",
        "The Earth is the cradle of humanity, but one cannot remain in the cradle forever. - Konstantin Tsiolkovsky",
        "To confine our attention to terrestrial matters would be to limit the human spirit. - Stephen Hawking",
        "In space, no one can hear you scream. - Alien (1979)",
        "Across the sea of space, the stars are other suns. - Carl Sagan",
        "The universe is under no obligation to make sense to you. - Neil deGrasse Tyson",
        "Space exploration is a force of nature unto itself that no other force in society can rival. - Neil deGrasse Tyson",
        "We choose to go to the Moon! - John F. Kennedy",
        "Imagination will often carry us to worlds that never were, but without it we go nowhere. - Carl Sagan",
        "We are an impossibility in an impossible universe. - Ray Bradbury",
        "Time and space are modes by which we think and not conditions in which we live. - Albert Einstein",
        "Somewhere, something incredible is waiting to be known. - Carl Sagan",
        "We are the cosmos made conscious. - Brian Cox",
        "Curiosity is the essence of our existence. - Gene Cernan",
        "For small creatures such as we, the vastness is bearable only through love. - Carl Sagan",
        "The sky is not the limit, it’s just the beginning. - Anonymous",
        "Astronomy compels the soul to look upward. - Plato",
        "We are going to steal the moon! - Gru",
    ],
};
